#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Apr 11 18:24:19 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3e24211987114250a139af1cb1279f19 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAPILU_behav xil_defaultlib.LAPILU -log elaborate.log"
xelab -wto 3e24211987114250a139af1cb1279f19 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot LAPILU_behav xil_defaultlib.LAPILU -log elaborate.log

