# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param ced.repoPaths /home/millocorona/.Xilinx/Vivado/2019.2/xhub/ced_store
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.cache/wt [current_project]
set_property parent.project_path /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/millocorona/.Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/LAPILU_Aritmetic_Components_PKG.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/NBitsFullAdder.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/NBitsZeroIdentifier.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/AritmeticLogicUnit.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/FlipFlopT.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/Flip_Flops_PKG.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/LAPILU_Modules_PKG.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/NBitsAcumulator.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/NBitsRegister.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/ProgramCounter.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/StepCounter.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/ProcessorStatusRegister.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/StackPointerRegister.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/MemoryAddressRegister.vhd
  /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/sources_1/new/LAPILU.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/constrs_1/imports/VHDL/Puertos-Nexys-A7-100T.xdc
set_property used_in_implementation false [get_files /home/millocorona/Desarrollo/VHDL/LAPILU-SimpleSoftCoreMicroProcessorUnit/LAPILU-SimpleSoftCoreMicroProcessorUnit.srcs/constrs_1/imports/VHDL/Puertos-Nexys-A7-100T.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LAPILU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LAPILU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LAPILU_utilization_synth.rpt -pb LAPILU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
